version: "3"

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      DATABASE_URL: postgresql://user:password@database:5432/task1
      CONFIG_NAME: DevConfig
    volumes:
      - ./core:/app/core
    ports:
      - 5000:5000
    depends_on:
      - database
    
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: task1
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ${HOME}/dbs/flask-tasks/pgdata_dev:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432